name: Bug report
description: Report a bug to help us improve. Inspired by the [GoDot](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml) bug report template.
body:

- type: markdown
  attributes:
    value: |
      - Read our [CONTRIBUTING.md guide](https://github.com/o3de/community/blob/main/CONTRIBUTING.md) on reporting bugs.
      - Write a descriptive issue title above.
      - Search [open](https://github.com/lmbr-pip/github-contributions-script/issues) and [closed](https://github.com/lmbr-pip/github-contributions-script/issues?q=is%3Aissue+is%3Aclosed+) issues to ensure it has not already been reported.
      - Verify that you are using a supported version.
- type: input
  attributes:
    label: Commit ID or Build Version
    description: >
      Please provide either the build version or the o3de/o3de Git commit hash your branch is built from.
      You can get the commit ID by running the `git rev-parse HEAD` command on your current branch or by looking at your Git history.
      If you are using a custom build, please test if your issue is reproducible on an O3DE/O3DE official branch or build.
    placeholder: f4760cf
  validations:
    required: true

- type: textarea
  attributes:
    label: Issue description
    description: |
      Describe your issue briefly. What doesn't work, and how do you expect it to work instead?
      You can include images or videos with drag and drop, and format code blocks or logs with <code>```</code> tags.
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
      List of steps or sample code that reproduces the issue. Having reproducible issues is a prerequisite for contributors to be able to solve them.
      If you include a minimal reproduction assets below, you can detail how to use then here.
    placeholder: |
      1. Go to '...'
      2. Click on '...'
      3. Select attached asset '...'
      4. Scroll down to '...'
      5. See error
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior
    description: |
      A clear and concise description of what you expected to happen. 

- type: textarea
  attributes:
    label: Actual Behavior
    description: |
      A clear and concise description of what you expected to happen.

- type: textarea
  attributes:
    label: Minimal project, config or assets to aid reproduction
    description: |
        [!Important!] Please provide sample assets needed to reproduce the issue, either as an [attachment](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) or as a link to a public asset in GitHub.

- type: textarea
  attributes:
    label: Screenshots/Video
    description: |
      If applicable, add screenshots and/or a video to help explain your problem.

- type: textarea
  attributes:
    label: Device/System Information
    description: |
        Please tell us about the desktop or device issue was encountered on. Please include whats relevant
    placeholder: |
        - Device: [e.g. PC, Mac, iPhone, Samsung] 
        - OS: [e.g. Windows, macOS, iOS, Android]
        - Version [e.g. 10, Monterey, Oreo]
        - CPU [e.g. Intel I9-9900k , Ryzen 5900x, ]
        - GPU [AMD 6800 XT, NVidia RTX 3090]
        - Memory [e.g. 16GB]
    validations:
      required: true
